name: Snyk Security

on:
  push:
    branches: ["main" ]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb

      - name: Authenticate snyk
        run: npx snyk auth bb233b41-1359-484d-888c-e79d3129a095
        
      #- name: Snyk Code test
        #run: snyk code test  --org=14e7bbc1-feba-4f59-b6dd-27d78c5eb73b --target-name='vulner' --report='vulner'|| true
        #run: snyk code test --report || true

      - name: Snyk Open Source monitor
        run: snyk monitor --org=14e7bbc1-feba-4f59-b6dd-27d78c5eb73b --target-name='vulner' --report='vulner'|| true

      - name: Snyk IaC test and report
        run: snyk iac test --report || true

      - name: Build a Docker image
        run: docker build -t your/image-to-test .
        
      - name: Snyk Container monitor
        run: snyk container monitor node:18.13.0 --file=Dockerfile --report='vulner'|| true

     
